repos:
- repo: https://github.com/Yelp/detect-secrets.git
  rev: v0.12.4
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/tests/.*
- repo: git://github.com/pecigonzalo/pre-commit-terraform-vars
  sha: master
  hooks:
    -   id: terraform-vars