module "platform" {
  source                       = "./0-platform"
  gcp_project                  = var.gcp_project
  cluster_name                 = var.cluster_name
  cluster_private              = var.cluster_private
  cluster_network              = var.cluster_network
  cluster_subnetwork           = var.cluster_subnetwork
  cluster_ip_allocation_policy = var.cluster_ip_allocation_policy
  zone                         = var.zone
  cluster_location             = var.cluster_location
  bucket_location              = var.bucket_location
  jenkins_x_namespace          = var.jenkins_x_namespace
  force_destroy                = var.force_destroy
  parent_domain                = var.parent_domain
  tls_email                    = var.tls_email
  create_ui_sa                 = var.create_ui_sa
  vault_url                    = var.vault_url
  enable_backup                = var.enable_backup
  velero_namespace             = var.velero_namespace
  velero_schedule              = var.velero_schedule
  velero_ttl                   = var.velero_ttl
  node_machine_type            = var.node_machine_type
  node_preemptible             = var.node_preemptible
  min_node_count               = var.min_node_count
  max_node_count               = var.max_node_count
  node_disk_size               = var.node_disk_size
  node_disk_type               = var.node_disk_type
  release_channel              = var.release_channel
  resource_labels              = var.resource_labels
  jx2                          = var.jx2
}

module "application" {
  source                    = "./1-application"
  gcp_project               = var.gcp_project
  access_token              = module.platform.access_token
  build_controller_sa_email = module.platform.build_controller_sa_email
  kaniko_sa_email           = module.platform.kaniko_sa_email
  tekton_sa_email           = module.platform.tekton_sa_email
  jxui_sa_email             = module.platform.jxui_sa_email
  dns_sa_email              = module.platform.dns_sa_email
  vault_sa_email            = module.platform.vault_sa_email

  backup_bucket_url      = module.platform.backup_bucket_url
  backup_velero_sa       = module.platform.backup_velero_sa
  backup_velero_sa_email = module.platform.backup_velero_sa_email
  vault_sa               = module.platform.vault_sa
  vault_name             = module.platform.vault_name
  vault_keyring          = module.platform.vault_keyring
  vault_key              = module.platform.vault_key
  vault_bucket_name      = module.platform.vault_bucket_name
  repository_storage_url = module.platform.repository_storage_url
  report_storage_url     = module.platform.report_storage_url
  log_storage_url        = module.platform.log_storage_url


  cluster_ip_allocation_policy = var.cluster_ip_allocation_policy
  cluster_ca_certificate       = module.platform.cluster_ca_certificate
  cluster_endpoint             = module.platform.cluster_endpoint
  zone                         = var.zone
  cluster_location             = var.cluster_location
  bucket_location              = var.bucket_location
  jenkins_x_namespace          = var.jenkins_x_namespace
  force_destroy                = var.force_destroy
  parent_domain                = var.parent_domain
  tls_email                    = var.tls_email
  create_ui_sa                 = var.create_ui_sa
  vault_url                    = var.vault_url
  enable_backup                = var.enable_backup
  velero_namespace             = var.velero_namespace
  velero_schedule              = var.velero_schedule
  velero_ttl                   = var.velero_ttl
  resource_labels              = var.resource_labels
  jx2                          = var.jx2
  git_owner_requirement_repos  = var.git_owner_requirement_repos
  dev_env_approvers            = var.dev_env_approvers
  lets_encrypt_production      = var.lets_encrypt_production
  webhook                      = var.webhook
  version_stream_url           = var.version_stream_url
  version_stream_ref           = var.version_stream_ref
}
